luku1 = input("Anna luku:")
luku1 = int(luku1)
luku2 = input("Anna toinen luku:")
luku2 = int(luku2)
luku3 = input("Anna kolmas luku:")
luku3 = int(luku3)
print("Numeroiden keskiarvo on: ", luku1+luku2+luku3/3)